#!/usr/bin/env sh

# bar settings
yabai -m config external_bar all:20:20

yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.55
yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_follows_focus          off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Window
yabai -m config window_placement             first_child
yabai -m config window_topmost               on
yabai -m config window_border                on
yabai -m config window_shadow                on
yabai -m config window_border_width          8
yabai -m config normal_window_border_color   0xff44475a
yabai -m config active_window_border_color   0xff6272a4
yabai -m config insert_window_border_color   0xff8E83B8

yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config active_window_opacity        1
yabai -m config normal_window_opacity        0.9

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# Running through float windows
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label slack
yabai -m space 4 --label other

# Float Windows
yabai -m rule --add app="System Settings" layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Zoom$" sticky=on layer=above manage=off
yabai -m rule --add app="^Jumpcut$" sticky=on layer=above manage=off

defaults write com.apple.finder DisableAllAnimations -bool true
